# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60e5166c3e53a50e90466e04d3e3115c63a68921d2cd0286bfeebcc3a4a685c1ff21b3d56940029325ea1ad835d7e786cb622fcdeebf041584b79d6e731b5069

test:
  secret_key_base: 6522ec3bef9836c5c44beb446b2531521c4fd67d6a37342438d926c0a5dc5fe68201f504be29ef51d4bf0ac6e8c80096e0a42c4c915a6de8b8921a0e4dca2d25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
